// The API bundle is generated by the Vercel build command before this function
// is packaged. Keeping the adapter JavaScript prevents Vercel from applying
// its standalone NodeNext typecheck to the TypeScript workspace source.
export default async function handler(req, res) {
  const { default: app } = await import(
    '../artifacts/api-server/dist-vercel/app.mjs'
  );
  return app(req, res);
}